### ISSUE TITLE
Calculated values in indexer

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/starknet-indexer#10]
We need to cache the computed values from StarkNet within the indexer. These values are computed on StarkNet and used around the place. You can of course view StarkNet for these values, but this is really slow. So we need to compute these values in the indexer and display/search for them in the client. We just need to decide what we compute in the indexer and what we compute in the client.

These should all be values on the Realm Model which can be fetched.

## EASY
These are just sums from static values.

**Population:**
Sum of all the buildings' population impact + troop population

**Culture:**
Sum of all the buildings' culture impact

**Food:**
Sum of all the buildings' food impact

## HARD

**Resources Accrued**
When a player settles a Realm a timestamp is recorded. When the player claims resources, this timestamp is updated to withdraw full days of resources. This means any left 'half-days are added back to the timestamp so the player does not lose these.
 
`now - timestamp / 86400 = n days`

**Vault Resources Accrued**
This is another timestamp that is recorded on settling. This gets updated either when the user is raided or when they have over 7 days of resources and they claim the full vault.

This value is what people look for when deciding to raid the realm or not.

`now - timestamp / 86400 = n days`

Question:
Currently, we are not emitting the time stamp. Should we emit both timestamps on every action?
- On settle
- On resource claim
- On raid
- On unsettle

This way we can just pipe it directly into the model

**Comment by tenoxious** [comment]
* Population, Culture, Food are already in the Building Models.
* We have the timestamp on every event. Settle/Unsettle/Raid are all events on a realm we currently index, and have the event timestamp.
* Resource claim -> we index, resource transfers. is there a way we can distinguish resource claims from any other resource transfer?

**Comment by ponderingdemocritus** [comment]
The only way we could is if we emitted another event on a resource claim. Currently for all resource events we are not emitting them again from the game contract as they get emitted from the base 1155 contract.

We could emit the resource amounts from the L02_Resources on claim, but then that is doubling up. We could just do an event like:

`ResourceClaim_1.emit(realmId, claimTime, vaultClaimTime)`

These would be emitted in the same tx as the transfer event so would be able to match them

I am thinking we emit `claimTime` and `vaultClaimTime` as these are the exact time of the vault claimed. Which could be less than the current time stamp, as any remaining days get added back into the timestamp so the player doesn't loose half days
