### ISSUE TITLE
Add Relic to battle report

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/starknet-indexer#13]
Add Relic result to `getRealmCombatResult`

The response should contain if the relic changed realms

**Comment by tenoxious** [comment]
![Screen Shot 2022-08-15 at 12 45 39 AM](https://user-images.githubusercontent.com/91395140/184597097-ea8dc284-4945-4feb-b1ea-f92ef4ad7ea2.png)
![Screen Shot 2022-08-15 at 12 50 17 AM](https://user-images.githubusercontent.com/91395140/184597103-592bf1df-5d5d-4c17-a6e7-728072a9ba1a.png)

added to both realm history
```
 data.realmClaimed <--- for attack event
 data.realmLost <--- for defend event
```

and combat result
```
realmLost
```

**Comment by tenoxious** [comment]
0 values mean no relic was lost during battle

**Comment by tenoxious** [comment]
value is originating realmId
