### ISSUE TITLE
Pillaged resources not flowing to events

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/starknet-indexer#14]
Resources Pillaged do not seem to be flowing through to events. I raided successfully, and the resources showed in the combat results screen, but they are not showing in the history data.

![Screenshot from 2022-08-13 16-38-10](https://user-images.githubusercontent.com/90423308/184472067-5b1171ac-840c-4376-a8a1-ce493a6ad8e9.png)

**Comment by tenoxious** [comment]
Please verify
