### ISSUE TITLE
Also add currency to market fetch

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaForAdventurers/starknet-indexer#16]
Currently, only token lpAmount is being cached - https://github.com/BibliothecaForAdventurers/starknet-indexer/blob/develop/app/entities/settling/ExchangeRate.ts

https://github.com/BibliothecaForAdventurers/realms-contracts/blob/feat/amm/contracts/exchange/Exchange_ERC20_1155.cairo#L1009

This returns

```
// This is $LORDS
currency_reserves : Uint256*, 

// This is the token
token_reserves : Uint256*,
```

We need both cached.

**Comment by tenoxious** [comment]
these are in now. new fields are
  currencyReserve
  tokenReserve

```
 getExchangeRates {
    hour
    date
    tokenId
    tokenName
    amount
    buyAmount
    sellAmount
    currencyReserve
    tokenReserve
    percentChange24Hr
  }
  ```
